name: WhiskyCollection
favicon: null
layout_spectrum: 0.22239980637095869
typography_spectrum: 0.01835982082411647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.9830708124209195
  lightness: 0.6824637125246227
  saturation: 0.832062820205465
  rhythmicContrast: 0.26142634940333664
purpose: []
