name: WhiskyCollection
favicon: null
layout_spectrum: 0.15662345988675952
typography_spectrum: 0.01835982082411647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.0076020939741283655
  lightness: 0.012807144550606608
  saturation: 0.8243996289093047
  rhythmicContrast: 0.693857979029417
purpose: []
